###########
# site.url, site.title

url:   'http://scilifelabcourses.github.io/courses'
title: 'SciLifeLab Courses'
google_analytics: 'UA-23985298-11'


########
# more settings

# markdown: redcarpet
# highlighter: pygments
# redcarpet:
#   extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript", "with_toc_data"]

markdown: redcarpet
pygments: true

sass:
  sass_dir: css
  style:    expanded



exclude:
- README.md


safe: true
lsi: false
