###########
# site.url, site.title

url:   'http://scilifelab.github.io/courses'
title: 'SciLifeLab Courses'
google_analytics: 'UA-23985298-11'


########
# more settings

markdown: kramdown

pygments: true

sass:
  sass_dir: css
  style:    expanded



exclude:
- README.md


safe: true
lsi: false
